apiVersion: apps/v1
kind: Deployment
metadata:
  name: vigo-auth-organisation-selector-frontend
spec:
    spec:
      containers:
        - name: vigo-auth-organisation-selector-frontend
          image: ghcr.io/fintlabs/vigo-auth-organisation-selector-frontend:sha-0000000
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
 
