apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flais.yaml
  - ingress-route.yaml
commonLabels:
  app.kubernetes.io/name: vigo-auth-organisation-selector-frontend
  app.kubernetes.io/instance: vigo-auth-organisation-selector-frontend
  app.kubernetes.io/version: "latest"
  app.kubernetes.io/managed-by: GA
  app.kubernetes.io/component: selector frontend
  app.kubernetes.io/part-of: fint-core-v2
  fintlabs.no/team: core
  fintlabs.no/org-id: fintlabs.no