apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: auth-selector-frontend
  name: auth-selector-frontend
spec:
  ports:
    - name: "8080"
      port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: auth-selector-frontend
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: auth-selector-frontend
  labels:
    app: auth-selector-frontend
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`auth.felleskomponent.no`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: auth-selector-frontend
          port: 8080
      middlewares:
        - name: auth-selector-forward
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: auth-selector-frontend
  name: auth-selector-frontend
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: auth-selector-frontend
  template:
    metadata:
      labels:
        io.kompose.service: auth-selector-frontend
    spec:
      restartPolicy: Always
      containers:
        - image: fintlabsacr.azurecr.io/auth-selector-frontend:dummy
          name: auth-selector-frontend
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
          ports:
            - containerPort: 8080
          env:
            - name: TZ
              value: Europe/Oslo
